services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: niall-otel-collector
    ports:
      - 1888:1888
      - 8888:8888
      - 8889:8889
      - 13133:13133
      - 4317:4317
      - 4318:4318
      - 55679:55679
    volumes:
      - ./etc/otel-collector.yaml:/etc/otel-collector.yaml
    command: --config=/etc/otel-collector.yaml
    depends_on:
      - tempo
      - prometheus

  tempo:
    image: grafana/tempo:latest
    container_name: niall-tempo
    ports:
      - 14268
      - 3200
      - 4317
      - 4318
      - 9411
    volumes:
      - ./etc/tempo.yaml:/etc/tempo.yaml
    command: -config.file=/etc/tempo.yaml

  loki:
    image: grafana/loki:latest
    container_name: niall-loki
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100:3100
    volumes:
      - ./etc/loki.yaml:/etc/loki/loki.yaml
    command: -config.file=/etc/loki/loki.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: niall-promtail
    volumes:
      - ./etc/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: niall-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: niall-grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
      - tempo
      - loki

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.6
    container_name: niall-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.6
    container_name: niall-kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    container_name: niall-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: niall
      MONGO_INITDB_ROOT_PASSWORD: yourvoicematters

  shop:
    container_name: niall-shop
    build:
      context: .
      dockerfile: apps/shop/Dockerfile
    ports:
      - 9000:9000
    environment:
      MONGO_URI: mongodb://niall:yourvoicematters@mongo:27017
      MONGO_DB: test
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: pets
      OTEL_METRIC_PORT: 8081
      OTEL_TRACE_URL: http://otel-collector:4318
    depends_on:
      - kafka
      - mongo

  indexer:
    container_name: niall-indexer
    build:
      context: .
      dockerfile: apps/indexer/Dockerfile
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: pets
      KAFKA_GROUP_ID: indexer
      OTEL_METRIC_PORT: 8081
      OTEL_TRACE_URL: http://otel-collector:4318
    depends_on:
      - kafka
